apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.businessLayer.name }}-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.businessLayer.name }}
    helm.sh/chart: {{ include "takeon-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.businessLayer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.businessLayer.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.businessLayer.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.businessLayer.name }}
          image: "{{ .Values.businessLayer.image.repository }}:{{ .Values.businessLayer.image.tag }}"
          imagePullPolicy: {{ .Values.businessLayer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.businessLayer.resources | nindent 12 }}
      {{- with .Values.businessLayer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.businessLayer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.businessLayer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
