apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dbLayer.name }}-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.dbLayer.name }}
    helm.sh/chart: {{ include "takeon-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.dbLayer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.dbLayer.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.dbLayer.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.dbLayer.name }}
          image: "{{ .Values.dbLayer.image.repository }}:{{ .Values.dbLayer.image.tag }}"
          imagePullPolicy: {{ .Values.dbLayer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: datasource_username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: datasource_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-name
                  key: DB_NAME
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: db-server
                  key: DB_SERVER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-port
                  key: DB_PORT
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - c
              - /opt/mssql-tools/bin/sqlcmd -U sa -P ${DATASOURCE_PASSWORD} -Q "SELECT @@SERVERNAME" > /sql_scripts/output
            initialDelaySeconds: 190
            periodSeconds: 20
          resources:
            {{- toYaml .Values.dbLayer.resources | nindent 12 }}
      {{- with .Values.dbLayer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.dbLayer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.dbLayer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}